#ifndef UBERARCHIVE_H_
#define UBERARCHIVE_H_

#include <stdint.h>

extern "C" {
    extern const uint8_t UBERARCHIVE_PACKAGE[];
    extern int UBERARCHIVE_DEFAULT_OFFSET;
    extern int UBERARCHIVE_DEFAULT_SIZE;
}
#define UBERARCHIVE_DEFAULT_DATA (UBERARCHIVE_PACKAGE + UBERARCHIVE_DEFAULT_OFFSET)

#endif
