import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: {
    Guides: [
      "guides/getting-started",
      "guides/asset-loading",
      "guides/transformation",
      "guides/skybox",
      "guides/physics"
    ],
    API: [
      {
        type: "autogenerated",
        dirName: "api",
      },
    ],
  },
};

export default sidebars;
