import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  sidebar: {
    Guides: ["guides/getting-started"],
    API: [
      {
        type: "autogenerated",
        dirName: "api",
      },
    ],
  },
};

export default sidebars;
